import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :banking_web, BankingWeb.Endpoint,
  url: [host: "banking-web.fly.dev", port: 8080],
  cache_static_manifest: "priv/static/cache_manifest.json"
